name: dart_date
description: Date manipulation library. DateTime extensions. Also includes an Interval object.
version: 1.0.9
homepage: https://github.com/xantiagoma/dart_date

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.17.0-nullsafety.2
  timeago: ^2.0.29

dev_dependencies:
  test: ^1.15.7
